### ISSUE TITLE
Add custom install instruction

### ISSUE THREAD

**Issue by ThomasBergman1** [indeedeng/imhotep#12]
Would like to do a custom install in AWS.
As we manage so much in AWS we would prefer a custom install we can control.

This is main thing preventing us from moving imhotep into an offical supported tool.

**Comment by hnarasaki** [comment]
Is this covered in https://opensource.indeedeng.io/imhotep/docs/quick-start/ & https://opensource.indeedeng.io/imhotep/docs/aws/ ?
