### ISSUE TITLE
Imhotep Error Messages reference indeed internal wiki

### ISSUE THREAD

**Issue by ThomasBergman1** [indeedeng/imhotep#16]
I saw an error like this when doing a particularly heavy query.

Query failed: 
Looks like the IQL server got overloaded and is restarting. 
Please take a look at your query and consider if it is too heavy. 
Wiki: 
https://wiki.indeed.com/display/INTEL/_Performance+Considerations+for+IQL+usage

**Comment by youknowjack** [comment]
@agrover-indeed if we can get a version of this content on the imhotep doc site, we can update that URL.

**Comment by hnarasaki** [comment]
I'm interested in helping out with this change.

**Comment by hnarasaki** [comment]
I updated troubleshooting.md to include "Performance Considerations for IQL usage" information from the internal Wiki.

Now the URL in the error message can be updated from https://wiki.indeed.com/display/INTEL/_Performance+Considerations+for+IQL+usage to http://opensource.indeedeng.io/imhotep/docs/troubleshooting/.

**Comment by tate-indeed** [comment]
I reviewed these doc pull requests and the information @hnarasaki added seems fine. The writers will take a pass at a language/style review now that the content is live.

**Comment by youknowjack** [comment]
Kamino closed and cloned this issue to [indeedeng/iql](https://github.com/indeedeng/iql/issues/11)
