### ISSUE TITLE
Imhotep Daemon doesn't shut down properly for supervisor

### ISSUE THREAD

**Issue by youknowjack** [indeedeng/imhotep#19]
While trying to help someone debug an issue in the forum recently, I noticed that after running "sudo /usr/local/bin/supervisorctl restart ImhotepDaemonMain", the old java process remained alongside the new one. There is some evidence that was causing problems with queries. I was also able to see that "sudo /usr/local/bin/supervisorctl stop ImhotepDaemonMain" was not resulting in the daemon process going away.

**Comment by kazysgurskas** [comment]
Stumbled upon this while trying to restart the daemon process. Your setup has ```command=/opt/imhotep/imhotep.sh``` as the supervisor command. As the script spawns a child java process, supervisor has no knowledge of it and does not stop it. You should add ```stopasgroup=true``` to the config in order to stop the whole process group.
