### ISSUE TITLE
Add a link to builder directory in Imhotep gh-pages

### ISSUE THREAD

**Issue by youknowjack** [indeedeng/imhotep#38]
I set up a builder directory in the Github wiki here:
https://github.com/indeedeng/imhotep/wiki/Imhotep-Builder-Directory

I chose the wiki for ease of addition to the directory. The Imhotep documentation in the gh-pages branch should be updated to link to the directory.

**Comment by hnarasaki** [comment]
@youknowjack Was this merged? If so, should this issue be closed out?

**Comment by youknowjack** [comment]
Yes, it was merged.
