### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of commons-io:commons-io:jar

### ISSUE THREAD

**Issue by Bing-ok** [indeedeng/imhotep#44]
## Issue description
Hi, there are multiple versions of **_commons-io:commons-io_** in **_imhotep-master\imhotep-archive_**. As shown in the following dependency tree, library **_commons-io:commons-io:2.4_** is transitively introduced by **_org.apache.hadoop:hadoop-client:2.6.0-cdh5.4.11_**, but has been managed to be version **_1.4_**.

However, several methods defined in shadowed version **_commons-io:commons-io:2.4_** are referenced by client project via **_org.apache.hadoop:hadoop-client:2.6.0-cdh5.4.11_**, but missing in the actually loaded version **_commons-io:commons-io:1.4_**.

For instance, the following missing methods(defined in **_commons-io:commons-io:2.4_**) are actually referenced by **_imhotep-master\imhotep-archive_**, which will introduce a runtime error(i.e., "NoSuchMethodErrors") into **_imhotep-master\imhotep-archive_**.

**_1. org.apache.commons.io.IOUtils: void closeQuietly(java.net.Socket)_** is invoked by **_imhotep-master\imhotep-archive_** via the following path:
<pre><code>
paths------
&lt;com.indeed.imhotep.archive.compression.NoCompressionInputStream: int read(byte[],int,int)&gt; imhotep-master\imhotep-archive\target\classes
&lt;org.apache.hadoop.hdfs.DFSInputStream: int read(byte[],int,int)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.DFSInputStream: int readWithStrategy(org.apache.hadoop.hdfs.DFSInputStream$ReaderStrategy,int,int)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.DFSInputStream: org.apache.hadoop.hdfs.protocol.DatanodeInfo blockSeekTo(long)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.BlockReaderFactory: org.apache.hadoop.hdfs.BlockReader build()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.BlockReaderFactory: org.apache.hadoop.hdfs.BlockReader getRemoteBlockReaderFromTcp()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.BlockReaderFactory: org.apache.hadoop.hdfs.BlockReaderFactory$BlockReaderPeer nextTcpPeer()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.server.namenode.NamenodeFsck$1: org.apache.hadoop.hdfs.net.Peer newConnectedPeer(java.net.InetSocketAddress,org.apache.hadoop.security.token.Token,org.apache.hadoop.hdfs.protocol.DatanodeID)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.commons.io.IOUtils: void closeQuietly(java.net.Socket)&gt;
</code></pre>

**_2. org.apache.commons.io.IOUtils: void closeQuietly(java.io.Closeable)_** is invoked by **_imhotep-master\imhotep-archive_** via the following path:
<pre><code>
paths------
&lt;com.indeed.imhotep.archive.compression.GzipCompressionInputStream: int read(byte[],int,int)&gt; imhotep-master\imhotep-archive\target\classes
&lt;org.apache.hadoop.hdfs.DFSInputStream: int read(byte[],int,int)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.DFSInputStream: int readWithStrategy(org.apache.hadoop.hdfs.DFSInputStream$ReaderStrategy,int,int)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.DFSInputStream: org.apache.hadoop.hdfs.protocol.DatanodeInfo blockSeekTo(long)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.BlockReaderFactory: org.apache.hadoop.hdfs.BlockReader build()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.BlockReaderFactory: org.apache.hadoop.hdfs.BlockReader getRemoteBlockReaderFromDomain()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.BlockReaderFactory: org.apache.hadoop.hdfs.BlockReaderFactory$BlockReaderPeer nextDomainPeer()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.shortcircuit.DomainSocketFactory: org.apache.hadoop.net.unix.DomainSocket createSocket(org.apache.hadoop.hdfs.shortcircuit.DomainSocketFactory$PathInfo,int)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.commons.io.IOUtils: void closeQuietly(java.io.Closeable)&gt;
</code></pre>

**_3. org.apache.commons.io.input.BoundedInputStream: void init (java.io.InputStream,long)_** is invoked by **_imhotep-master\imhotep-archive_** via the following path:
<pre><code>
paths------
&lt;com.indeed.imhotep.archive.compression.NoCompressionInputStream: int read(byte[],int,int)&gt; githubProject\imhotep-master\imhotep-archive\target\classes
&lt;org.apache.hadoop.hdfs.web.ByteRangeInputStream: int read(byte[],int,int)&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.web.ByteRangeInputStream: java.io.InputStream getInputStream()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.hadoop.hdfs.web.ByteRangeInputStream: java.io.InputStream openInputStream()&gt; Repositories\org\apache\hadoop\hadoop-hdfs\2.6.0-cdh5.4.11\hadoop-hdfs-2.6.0-cdh5.4.11.jar
&lt;org.apache.commons.io.input.BoundedInputStream: void init (java.io.InputStream,long)&gt;
</code></pre>

## Suggested fixing solutions
1. Use configuration attribute &lt;dependencyManagement&gt; to unify the version of library **_commons-io:commons-io_** to be **_2.4_** in imhotep-master\imhotep-archive's pom file.
2. Declare a direct dependency **_commons-io:commons-io:2.4_** in the pom file of **_imhotep-master\imhotep-archive_**, to override **_commons-io:commons-io_**'s managed version.

Please let me know which solution do you prefer? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
[INFO] com.indeed:imhotep-archive:jar:1.0.11-SNAPSHOT
[INFO] \- org.apache.hadoop:hadoop-client:jar:2.6.0-cdh5.4.11:compile
[INFO]    +- org.apache.hadoop:hadoop-common:jar:2.6.0-cdh5.4.11:compile
[INFO]    |  \- <b>commons-io:commons-io:jar:1.4:compile (version managed from 2.4)</b>
[INFO]    +- org.apache.hadoop:hadoop-hdfs:jar:2.6.0-cdh5.4.11:compile
[INFO]    |  \- (commons-io:commons-io:jar:1.4:compile - version managed from 2.4; omitted for duplicate)
[INFO]    \- org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.6.0-cdh5.4.11:compile
[INFO]       \- org.apache.hadoop:hadoop-yarn-common:jar:2.6.0-cdh5.4.11:compile
[INFO]          \- (commons-io:commons-io:jar:1.4:compile - version managed from 2.4; omitted for duplicate)
</code></pre>

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @DuaneOBrien

**Comment by Bing-ok** [comment]
@youknowjack Could you please help me review this issue? Thank you very much.

**Comment by Anusien** [comment]
@mmorrisontx or @mkw  can you take a look at this please?

**Comment by DuaneOBrien** [comment]
Hi @Bing-ok - apologies for the extended delay responding to this issue. The OSS Lifecycle badge isn't an accurate reflection of the status of this project. We are planning to announce a sunset of the open source version of Imhotep in the near future. While we still use Imhotep heavily at Indeed, community interest has been limited. 

That said, if you're using Imhotep or experimenting with it, I'd love to hear more about your experience if you're willing to share. I'd be happy to jump on a video call to discuss.
