### ISSUE TITLE
Add Minio remote file support

### ISSUE THREAD

**Issue by youknowjack** [indeedeng/imhotep#5]
As an alternative to S3, support accessing remote files in a Minio (open source S3 compatible) service.

**Comment by jpitz** [comment]
From the way that the docs read on their github, it sounds like it is API compatible with the S3 client. The team does produce their own Java API that can communicate with any similar storage mechanism.

https://docs.minio.io/docs/aws-cli-with-minio

They even have an example on how to use the existing AWS SDK to communicate with a minio server:

https://docs.minio.io/docs/how-to-use-aws-sdk-for-java-with-minio-server

There _may_ not be too much to do here.
